name: API tests - ServeRest
on: push
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Secrets
        run: |
          echo "Validating Secrets..."

          # Lista de variáveis esperadas
          secrets_list=(
            "USER_DATA"
            "USER_EMAIL"
            "USER_PASSWORD"
            "NEW_USER_DATA"
            "NOME"
            "EMAIL"
            "PASSWORD"
            "ADMIN"
            "PRODUCT_DATA"
            "NOME_PRODUTO"
            "PRECO"
            "DESCRICAO"
            "QUANTIDADE"
            "CYPRESS_RECORD_KEY"
          )

          # Verifica se cada secret está definido
          for secret in "${secrets_list[@]}"; do
            if [[ -z "${!secret}" ]]; then
              echo "::error:: Secret $secret is missing or empty!"
            else
              echo "✅ $secret is set"
            fi
          done

          # Testa se os secrets que deveriam ser JSON são válidos
          json_secrets=("CYPRESS_USER_DATA" "CYPRESS_NEW_USER_DATA" "CYPRESS_PRODUCT_DATA")
          for json_secret in "${json_secrets[@]}"; do
            if echo "${!json_secret}" | jq empty 2>/dev/null; then
              echo "✅ $json_secret is valid JSON"
            else
              echo "::error:: $json_secret is not valid JSON!"
            fi
          done

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
        env:
          CYPRESS_USER_DATA: ${{ secrets.USER_DATA }}
          CYPRESS_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          CYPRESS_NEW_USER_DATA: ${{ secrets.NEW_USER_DATA }}
          CYPRESS_NOME: ${{ secrets.NOME }}
          CYPRESS_EMAIL: ${{ secrets.EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
          CYPRESS_ADMIN: ${{ secrets.ADMIN }}
          CYPRESS_PRODUCT_DATA: ${{ secrets.PRODUCT_DATA }}
          CYPRESS_NOME_PRODUTO: ${{ secrets.NOME_PRODUTO }}
          CYPRESS_PRECO: ${{ secrets.PRECO }}
          CYPRESS_DESCRICAO: ${{ secrets.DESCRICAO }}
          CYPRESS_QUANTIDADE: ${{ secrets.QUANTIDADE }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
